/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_NAKI3D_COMMON_PROTOCOL_PROTO_FILES_CEC_PB_H_INCLUDED
#define PB_NAKI3D_COMMON_PROTOCOL_PROTO_FILES_CEC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Reverse conrtol */
typedef enum _naki3d_common_protocol_CECAction {
    naki3d_common_protocol_CECAction_POWER_ON = 0,
    naki3d_common_protocol_CECAction_POWER_OFF = 1 /* TODO: Brightness, saturation, etc... */
} naki3d_common_protocol_CECAction;

/* Struct definitions */
typedef struct _naki3d_common_protocol_CECMessage {
    naki3d_common_protocol_CECAction action;
} naki3d_common_protocol_CECMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _naki3d_common_protocol_CECAction_MIN naki3d_common_protocol_CECAction_POWER_ON
#define _naki3d_common_protocol_CECAction_MAX naki3d_common_protocol_CECAction_POWER_OFF
#define _naki3d_common_protocol_CECAction_ARRAYSIZE ((naki3d_common_protocol_CECAction)(naki3d_common_protocol_CECAction_POWER_OFF+1))

#define naki3d_common_protocol_CECMessage_action_ENUMTYPE naki3d_common_protocol_CECAction


/* Initializer values for message structs */
#define naki3d_common_protocol_CECMessage_init_default {_naki3d_common_protocol_CECAction_MIN}
#define naki3d_common_protocol_CECMessage_init_zero {_naki3d_common_protocol_CECAction_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define naki3d_common_protocol_CECMessage_action_tag 1

/* Struct field encoding specification for nanopb */
#define naki3d_common_protocol_CECMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1)
#define naki3d_common_protocol_CECMessage_CALLBACK NULL
#define naki3d_common_protocol_CECMessage_DEFAULT NULL

extern const pb_msgdesc_t naki3d_common_protocol_CECMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define naki3d_common_protocol_CECMessage_fields &naki3d_common_protocol_CECMessage_msg

/* Maximum encoded size of messages (where known) */
#define naki3d_common_protocol_CECMessage_size   2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
