/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "proto_files/discovery.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(naki3d_common_protocol_AvailableSensors, naki3d_common_protocol_AvailableSensors, AUTO)


PB_BIND(naki3d_common_protocol_SensorDescriptor, naki3d_common_protocol_SensorDescriptor, AUTO)




