/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "proto_files/empty.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(naki3d_common_protocol_Empty, naki3d_common_protocol_Empty, AUTO)



