/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_NAKI3D_COMMON_PROTOCOL_PROTO_FILES_SENSORS_PB_H_INCLUDED
#define PB_NAKI3D_COMMON_PROTOCOL_PROTO_FILES_SENSORS_PB_H_INCLUDED
#include <pb.h>
#include "cec.pb.h"
#include "discovery.pb.h"
#include "types.pb.h"
#include "empty.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* RasPi -> Device
 Message wrapper, same as above. */
typedef struct _naki3d_common_protocol_SensorDataMessage {
    pb_callback_t path;
    uint64_t timestamp; /* Microseconds since startup (Camera timing is in microseconds, may as well keep it) */
    pb_size_t which_data;
    union {
        naki3d_common_protocol_Empty void;
        bool bool;
        int32_t integer;
        float float;
        pb_callback_t string;
        naki3d_common_protocol_Vector2Data vector2;
        naki3d_common_protocol_Vector3Data vector3;
    } data;
} naki3d_common_protocol_SensorDataMessage;

typedef struct _naki3d_common_protocol_SensorMessage {
    pb_size_t which_message;
    union {
        naki3d_common_protocol_SensorDataMessage data;
        naki3d_common_protocol_SensorDescriptor descriptor;
    } message;
} naki3d_common_protocol_SensorMessage;

/* Device -> RasPi
 Message wrapper, same as above. */
typedef struct _naki3d_common_protocol_SensorControlMessage {
    pb_callback_t hostname;
    pb_size_t which_message;
    union {
        naki3d_common_protocol_CECMessage cec_message;
    } message;
} naki3d_common_protocol_SensorControlMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define naki3d_common_protocol_SensorDataMessage_init_default {{{NULL}, NULL}, 0, 0, {google_protobuf_Empty_init_default}}
#define naki3d_common_protocol_SensorMessage_init_default {0, {naki3d_common_protocol_SensorDataMessage_init_default}}
#define naki3d_common_protocol_SensorControlMessage_init_default {{{NULL}, NULL}, 0, {naki3d_common_protocol_CECMessage_init_default}}
#define naki3d_common_protocol_SensorDataMessage_init_zero {{{NULL}, NULL}, 0, 0, {google_protobuf_Empty_init_zero}}
#define naki3d_common_protocol_SensorMessage_init_zero {0, {naki3d_common_protocol_SensorDataMessage_init_zero}}
#define naki3d_common_protocol_SensorControlMessage_init_zero {{{NULL}, NULL}, 0, {naki3d_common_protocol_CECMessage_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define naki3d_common_protocol_SensorDataMessage_path_tag 1
#define naki3d_common_protocol_SensorDataMessage_timestamp_tag 2
#define naki3d_common_protocol_SensorDataMessage_void_tag 16
#define naki3d_common_protocol_SensorDataMessage_bool_tag 17
#define naki3d_common_protocol_SensorDataMessage_integer_tag 18
#define naki3d_common_protocol_SensorDataMessage_float_tag 19
#define naki3d_common_protocol_SensorDataMessage_string_tag 20
#define naki3d_common_protocol_SensorDataMessage_vector2_tag 21
#define naki3d_common_protocol_SensorDataMessage_vector3_tag 22
#define naki3d_common_protocol_SensorMessage_data_tag 1
#define naki3d_common_protocol_SensorMessage_descriptor_tag 2
#define naki3d_common_protocol_SensorControlMessage_hostname_tag 1
#define naki3d_common_protocol_SensorControlMessage_cec_message_tag 17

/* Struct field encoding specification for nanopb */
#define naki3d_common_protocol_SensorDataMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,void,data.void),  16) \
X(a, STATIC,   ONEOF,    BOOL,     (data,bool,data.bool),  17) \
X(a, STATIC,   ONEOF,    INT32,    (data,integer,data.integer),  18) \
X(a, STATIC,   ONEOF,    FLOAT,    (data,float,data.float),  19) \
X(a, CALLBACK, ONEOF,    STRING,   (data,string,data.string),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,vector2,data.vector2),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,vector3,data.vector3),  22)
#define naki3d_common_protocol_SensorDataMessage_CALLBACK pb_default_field_callback
#define naki3d_common_protocol_SensorDataMessage_DEFAULT NULL
#define naki3d_common_protocol_SensorDataMessage_data_void_MSGTYPE google_protobuf_Empty
#define naki3d_common_protocol_SensorDataMessage_data_vector2_MSGTYPE naki3d_common_protocol_Vector2Data
#define naki3d_common_protocol_SensorDataMessage_data_vector3_MSGTYPE naki3d_common_protocol_Vector3Data

#define naki3d_common_protocol_SensorMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,data,message.data),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,descriptor,message.descriptor),   2)
#define naki3d_common_protocol_SensorMessage_CALLBACK NULL
#define naki3d_common_protocol_SensorMessage_DEFAULT NULL
#define naki3d_common_protocol_SensorMessage_message_data_MSGTYPE naki3d_common_protocol_SensorDataMessage
#define naki3d_common_protocol_SensorMessage_message_descriptor_MSGTYPE naki3d_common_protocol_SensorDescriptor

#define naki3d_common_protocol_SensorControlMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   hostname,          1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,cec_message,message.cec_message),  17)
#define naki3d_common_protocol_SensorControlMessage_CALLBACK pb_default_field_callback
#define naki3d_common_protocol_SensorControlMessage_DEFAULT NULL
#define naki3d_common_protocol_SensorControlMessage_message_cec_message_MSGTYPE naki3d_common_protocol_CECMessage

extern const pb_msgdesc_t naki3d_common_protocol_SensorDataMessage_msg;
extern const pb_msgdesc_t naki3d_common_protocol_SensorMessage_msg;
extern const pb_msgdesc_t naki3d_common_protocol_SensorControlMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define naki3d_common_protocol_SensorDataMessage_fields &naki3d_common_protocol_SensorDataMessage_msg
#define naki3d_common_protocol_SensorMessage_fields &naki3d_common_protocol_SensorMessage_msg
#define naki3d_common_protocol_SensorControlMessage_fields &naki3d_common_protocol_SensorControlMessage_msg

/* Maximum encoded size of messages (where known) */
/* naki3d_common_protocol_SensorDataMessage_size depends on runtime parameters */
/* naki3d_common_protocol_SensorMessage_size depends on runtime parameters */
/* naki3d_common_protocol_SensorControlMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
