/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "proto_files/sensors.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(naki3d_common_protocol_SensorDataMessage, naki3d_common_protocol_SensorDataMessage, AUTO)


PB_BIND(naki3d_common_protocol_SensorMessage, naki3d_common_protocol_SensorMessage, AUTO)


PB_BIND(naki3d_common_protocol_SensorControlMessage, naki3d_common_protocol_SensorControlMessage, AUTO)



