/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "proto_files/types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(naki3d_common_protocol_Vector3Data, naki3d_common_protocol_Vector3Data, AUTO)


PB_BIND(naki3d_common_protocol_Vector2Data, naki3d_common_protocol_Vector2Data, AUTO)



