/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "naki_sensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(naki3d_common_protocol_UltrasonicDistanceData, naki3d_common_protocol_UltrasonicDistanceData, AUTO)


PB_BIND(naki3d_common_protocol_LightLevelData, naki3d_common_protocol_LightLevelData, AUTO)


PB_BIND(naki3d_common_protocol_PirMovementData, naki3d_common_protocol_PirMovementData, AUTO)


PB_BIND(naki3d_common_protocol_SensorMessage, naki3d_common_protocol_SensorMessage, AUTO)


PB_BIND(naki3d_common_protocol_SensorInfo, naki3d_common_protocol_SensorInfo, AUTO)


PB_BIND(naki3d_common_protocol_SensorList, naki3d_common_protocol_SensorList, AUTO)


PB_BIND(naki3d_common_protocol_SensorListRequest, naki3d_common_protocol_SensorListRequest, AUTO)


PB_BIND(naki3d_common_protocol_SensorControlMessage, naki3d_common_protocol_SensorControlMessage, AUTO)





