/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_NAKI3D_COMMON_PROTOCOL_PROTO_FILES_NAKI_SENSOR_PB_H_INCLUDED
#define PB_NAKI3D_COMMON_PROTOCOL_PROTO_FILES_NAKI_SENSOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _naki3d_common_protocol_SensorType { 
    naki3d_common_protocol_SensorType_SENSOR_TYPE_GESTURE = 0, 
    naki3d_common_protocol_SensorType_SENSOR_TYPE_IMAGE = 1, 
    naki3d_common_protocol_SensorType_SENSOR_TYPE_DEPTH = 2, 
    naki3d_common_protocol_SensorType_SENSOR_TYPE_LIGHT = 3, 
    naki3d_common_protocol_SensorType_SENSOR_TYPE_MICROPHONE = 4, 
    naki3d_common_protocol_SensorType_SENSOR_TYPE_IR = 5, 
    naki3d_common_protocol_SensorType_SENSOR_TYPE_ULTRASONIC = 6 /* TODO: other sensors? */
} naki3d_common_protocol_SensorType;

typedef enum _naki3d_common_protocol_PirMovementEvent { 
    naki3d_common_protocol_PirMovementEvent_MOVEMENT_STARTED = 0, 
    naki3d_common_protocol_PirMovementEvent_MOVEMENT_STOPPED = 1 
} naki3d_common_protocol_PirMovementEvent;

/* Struct definitions */
typedef struct _naki3d_common_protocol_SensorList { 
    pb_callback_t sensors; 
} naki3d_common_protocol_SensorList;

typedef struct _naki3d_common_protocol_SensorListRequest { 
    char dummy_field;
} naki3d_common_protocol_SensorListRequest;

typedef struct _naki3d_common_protocol_LightLevelData { 
    float level; 
} naki3d_common_protocol_LightLevelData;

typedef struct _naki3d_common_protocol_PirMovementData { 
    naki3d_common_protocol_PirMovementEvent event; 
} naki3d_common_protocol_PirMovementData;

/* Message wrapper, same as above. */
typedef struct _naki3d_common_protocol_SensorControlMessage { 
    pb_callback_t hostname; 
    pb_size_t which_message;
    union {
        naki3d_common_protocol_SensorListRequest sensor_list;
    } message; /* CECMessage cec_message = 17; */
} naki3d_common_protocol_SensorControlMessage;

typedef struct _naki3d_common_protocol_SensorInfo { 
    pb_callback_t sensor_name; 
    naki3d_common_protocol_SensorType type; 
} naki3d_common_protocol_SensorInfo;

/* RasPi -> Device */
typedef struct _naki3d_common_protocol_UltrasonicDistanceData { 
    float distance; 
} naki3d_common_protocol_UltrasonicDistanceData;

/* Message wrapper, same as above. */
typedef struct _naki3d_common_protocol_SensorMessage { 
    char sensor_id[32]; 
    uint64_t timestamp; /* Microseconds since startup (Camera timing is in microseconds, may as well keep it) */
    /* GestureData gesture = 16; // Keeping some space for extra info
HandMovementData hand_movement = 17;
BestUserChangedData best_user_changed = 18;
KeyboardUpdateData keyboard_update = 19;
MouseMoveData mouse_move = 20;
MouseButtonData mouse_button = 21;
MouseScrollData mouse_scroll = 22; */
    pb_size_t which_data;
    union {
        naki3d_common_protocol_UltrasonicDistanceData ultrasonic_distance;
        naki3d_common_protocol_LightLevelData light_level;
        naki3d_common_protocol_PirMovementData pir_movement;
    } data; 
} naki3d_common_protocol_SensorMessage;


/* Helper constants for enums */
#define _naki3d_common_protocol_SensorType_MIN naki3d_common_protocol_SensorType_SENSOR_TYPE_GESTURE
#define _naki3d_common_protocol_SensorType_MAX naki3d_common_protocol_SensorType_SENSOR_TYPE_ULTRASONIC
#define _naki3d_common_protocol_SensorType_ARRAYSIZE ((naki3d_common_protocol_SensorType)(naki3d_common_protocol_SensorType_SENSOR_TYPE_ULTRASONIC+1))

#define _naki3d_common_protocol_PirMovementEvent_MIN naki3d_common_protocol_PirMovementEvent_MOVEMENT_STARTED
#define _naki3d_common_protocol_PirMovementEvent_MAX naki3d_common_protocol_PirMovementEvent_MOVEMENT_STOPPED
#define _naki3d_common_protocol_PirMovementEvent_ARRAYSIZE ((naki3d_common_protocol_PirMovementEvent)(naki3d_common_protocol_PirMovementEvent_MOVEMENT_STOPPED+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define naki3d_common_protocol_UltrasonicDistanceData_init_default {0}
#define naki3d_common_protocol_LightLevelData_init_default {0}
#define naki3d_common_protocol_PirMovementData_init_default {_naki3d_common_protocol_PirMovementEvent_MIN}
#define naki3d_common_protocol_SensorMessage_init_default {"", 0, 0, {naki3d_common_protocol_UltrasonicDistanceData_init_default}}
#define naki3d_common_protocol_SensorInfo_init_default {{{NULL}, NULL}, _naki3d_common_protocol_SensorType_MIN}
#define naki3d_common_protocol_SensorList_init_default {{{NULL}, NULL}}
#define naki3d_common_protocol_SensorListRequest_init_default {0}
#define naki3d_common_protocol_SensorControlMessage_init_default {{{NULL}, NULL}, 0, {naki3d_common_protocol_SensorListRequest_init_default}}
#define naki3d_common_protocol_UltrasonicDistanceData_init_zero {0}
#define naki3d_common_protocol_LightLevelData_init_zero {0}
#define naki3d_common_protocol_PirMovementData_init_zero {_naki3d_common_protocol_PirMovementEvent_MIN}
#define naki3d_common_protocol_SensorMessage_init_zero {"", 0, 0, {naki3d_common_protocol_UltrasonicDistanceData_init_zero}}
#define naki3d_common_protocol_SensorInfo_init_zero {{{NULL}, NULL}, _naki3d_common_protocol_SensorType_MIN}
#define naki3d_common_protocol_SensorList_init_zero {{{NULL}, NULL}}
#define naki3d_common_protocol_SensorListRequest_init_zero {0}
#define naki3d_common_protocol_SensorControlMessage_init_zero {{{NULL}, NULL}, 0, {naki3d_common_protocol_SensorListRequest_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define naki3d_common_protocol_SensorList_sensors_tag 1
#define naki3d_common_protocol_LightLevelData_level_tag 1
#define naki3d_common_protocol_PirMovementData_event_tag 1
#define naki3d_common_protocol_SensorControlMessage_hostname_tag 1
#define naki3d_common_protocol_SensorControlMessage_sensor_list_tag 16
#define naki3d_common_protocol_SensorInfo_sensor_name_tag 1
#define naki3d_common_protocol_SensorInfo_type_tag 2
#define naki3d_common_protocol_UltrasonicDistanceData_distance_tag 1
#define naki3d_common_protocol_SensorMessage_sensor_id_tag 1
#define naki3d_common_protocol_SensorMessage_timestamp_tag 2
#define naki3d_common_protocol_SensorMessage_ultrasonic_distance_tag 23
#define naki3d_common_protocol_SensorMessage_light_level_tag 24
#define naki3d_common_protocol_SensorMessage_pir_movement_tag 26

/* Struct field encoding specification for nanopb */
#define naki3d_common_protocol_UltrasonicDistanceData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    distance,          1)
#define naki3d_common_protocol_UltrasonicDistanceData_CALLBACK NULL
#define naki3d_common_protocol_UltrasonicDistanceData_DEFAULT NULL

#define naki3d_common_protocol_LightLevelData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    level,             1)
#define naki3d_common_protocol_LightLevelData_CALLBACK NULL
#define naki3d_common_protocol_LightLevelData_DEFAULT NULL

#define naki3d_common_protocol_PirMovementData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    event,             1)
#define naki3d_common_protocol_PirMovementData_CALLBACK NULL
#define naki3d_common_protocol_PirMovementData_DEFAULT NULL

#define naki3d_common_protocol_SensorMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   sensor_id,         1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,ultrasonic_distance,data.ultrasonic_distance),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,light_level,data.light_level),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,pir_movement,data.pir_movement),  26)
#define naki3d_common_protocol_SensorMessage_CALLBACK NULL
#define naki3d_common_protocol_SensorMessage_DEFAULT NULL
#define naki3d_common_protocol_SensorMessage_data_ultrasonic_distance_MSGTYPE naki3d_common_protocol_UltrasonicDistanceData
#define naki3d_common_protocol_SensorMessage_data_light_level_MSGTYPE naki3d_common_protocol_LightLevelData
#define naki3d_common_protocol_SensorMessage_data_pir_movement_MSGTYPE naki3d_common_protocol_PirMovementData

#define naki3d_common_protocol_SensorInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   sensor_name,       1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2)
#define naki3d_common_protocol_SensorInfo_CALLBACK pb_default_field_callback
#define naki3d_common_protocol_SensorInfo_DEFAULT NULL

#define naki3d_common_protocol_SensorList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  sensors,           1)
#define naki3d_common_protocol_SensorList_CALLBACK pb_default_field_callback
#define naki3d_common_protocol_SensorList_DEFAULT NULL
#define naki3d_common_protocol_SensorList_sensors_MSGTYPE naki3d_common_protocol_SensorInfo

#define naki3d_common_protocol_SensorListRequest_FIELDLIST(X, a) \

#define naki3d_common_protocol_SensorListRequest_CALLBACK NULL
#define naki3d_common_protocol_SensorListRequest_DEFAULT NULL

#define naki3d_common_protocol_SensorControlMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   hostname,          1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,sensor_list,message.sensor_list),  16)
#define naki3d_common_protocol_SensorControlMessage_CALLBACK pb_default_field_callback
#define naki3d_common_protocol_SensorControlMessage_DEFAULT NULL
#define naki3d_common_protocol_SensorControlMessage_message_sensor_list_MSGTYPE naki3d_common_protocol_SensorListRequest

extern const pb_msgdesc_t naki3d_common_protocol_UltrasonicDistanceData_msg;
extern const pb_msgdesc_t naki3d_common_protocol_LightLevelData_msg;
extern const pb_msgdesc_t naki3d_common_protocol_PirMovementData_msg;
extern const pb_msgdesc_t naki3d_common_protocol_SensorMessage_msg;
extern const pb_msgdesc_t naki3d_common_protocol_SensorInfo_msg;
extern const pb_msgdesc_t naki3d_common_protocol_SensorList_msg;
extern const pb_msgdesc_t naki3d_common_protocol_SensorListRequest_msg;
extern const pb_msgdesc_t naki3d_common_protocol_SensorControlMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define naki3d_common_protocol_UltrasonicDistanceData_fields &naki3d_common_protocol_UltrasonicDistanceData_msg
#define naki3d_common_protocol_LightLevelData_fields &naki3d_common_protocol_LightLevelData_msg
#define naki3d_common_protocol_PirMovementData_fields &naki3d_common_protocol_PirMovementData_msg
#define naki3d_common_protocol_SensorMessage_fields &naki3d_common_protocol_SensorMessage_msg
#define naki3d_common_protocol_SensorInfo_fields &naki3d_common_protocol_SensorInfo_msg
#define naki3d_common_protocol_SensorList_fields &naki3d_common_protocol_SensorList_msg
#define naki3d_common_protocol_SensorListRequest_fields &naki3d_common_protocol_SensorListRequest_msg
#define naki3d_common_protocol_SensorControlMessage_fields &naki3d_common_protocol_SensorControlMessage_msg

/* Maximum encoded size of messages (where known) */
/* naki3d_common_protocol_SensorInfo_size depends on runtime parameters */
/* naki3d_common_protocol_SensorList_size depends on runtime parameters */
/* naki3d_common_protocol_SensorControlMessage_size depends on runtime parameters */
#define naki3d_common_protocol_LightLevelData_size 5
#define naki3d_common_protocol_PirMovementData_size 2
#define naki3d_common_protocol_SensorListRequest_size 0
#define naki3d_common_protocol_SensorMessage_size 52
#define naki3d_common_protocol_UltrasonicDistanceData_size 5

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
