/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PROTO_FILES_TEST_PB_H_INCLUDED
#define PB_PROTO_FILES_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SensorInfo { 
    int32_t value; 
} SensorInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorInfo_init_default                  {0}
#define SensorInfo_init_zero                     {0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorInfo_value_tag                     1

/* Struct field encoding specification for nanopb */
#define SensorInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    value,             1)
#define SensorInfo_CALLBACK NULL
#define SensorInfo_DEFAULT NULL

extern const pb_msgdesc_t SensorInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorInfo_fields &SensorInfo_msg

/* Maximum encoded size of messages (where known) */
#define SensorInfo_size                          11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
